" Enable pathogen
call pathogen#infect()

" Define leader mapping
let mapleader = ","

" No Vi Compatibility. That just sucks
set nocompatible

" Turn on color syntax highlighting
syntax enable

" BOM often causes trouble
set encoding=utf-8 nobomb

" Tell vim that lines following an indented line must have the same indentation as the previous line
set autoindent

" Tell vim to automatically insert one extra level of indentation in some cases
set smartindent

" Tell vim to display line numbers
set number

" Tell vim to highlight the current line in every window and update the highlight as the cursor moves
set cursorline

" Tell vim to try yo preserve column where cursor is positioned
set nostartofline

" Tell vim how many columns a tab counts for
set tabstop=4

" Indicate a fast terminal connection
set ttyfast

" Tell vim to start searching when you type the first character of the search string
set incsearch

" Tell vim to create <FILENAME>.un~ file whenever a file is edited
set undofile

" When a bracket is inserted, briefly jump to the matching one
set showmatch

" Tell vim how many columns text is indented with the reindent operations (<< and >>) and automatic C-style indentation
set shiftwidth=4

" Tell vim the number of spaces that a <Tab> counts for while performing editing operations
set softtabstop=4

" Tell vim to highlight all matches (shown in a different color)
set hlsearch

" Tell vim no to highlight any matches
"set nohls

" Tell vim to enable mouse support
" To make mouse selection behave as if mouse=a was not enabled, press Shift while selecting with the mouse
set mouse=a

" Tell vim to insert space characters whenever the tab key is pressed
" To enter a real tab character use Ctrl-V<Tab> key sequence
set expandtab

" Tell vim to show the line and column number of the cursor position, separated by a comma
set ruler

" Increase history from 20 default to 1000
set history=1000

" Convince Vim it can use 256 colors inside Gnome Terminal.
" Needs CSApprox plugin
set t_Co=256

" Only do this part when compiled with support for autocommands
if has("autocmd")
    " Enable file type detection
    filetype on
    " Enable loading the plugin files for specific file types
    filetype plugin on

    " Disable expandtab for makefiles
    autocmd FileType make setlocal noexpandtab
endif

if has("gui_gtk2")
  set guifont=Bitstream\ Vera\ Sans\ Mono\ 9,Fixed\ 9
  set guifontwide=Microsoft\ Yahei\ 9,WenQuanYi\ Zen\ Hei\ 9
endif

" Turn on omnicompletion
"set ofu=syntaxcomplete#Complete

" Define tagbar maps
let g:tagbar_usearrows = 1
nnoremap <leader>l :TagbarToggle<CR>

" Configure solarized
set background=dark
let g:solarized_termtrans=1
let g:solarized_termcolors=256
let g:solarized_contrast="high"
let g:solarized_visibility="high"
colorscheme solarized
call togglebg#map("<F5>")

" Configure NERDTree
map <F2> :NERDTreeToggle<CR>

" Configure ctags
"set tags=./tags;

" Configure fugitive
autocmd User fugitive
  \ if fugitive#buffer().type() =~# '^\%(tree\|blob\)$' |
  \   nnoremap <buffer> .. :edit %:h<CR> |
  \ endif
autocmd BufReadPost fugitive://* set bufhidden=delete
set statusline=%<%f\ %h%m%r%{fugitive#statusline()}%=%-14.(%l,%c%V%)\ %P

" Enable syntax highlighting for *.ejs
au BufNewFile,BufRead *.ejs set filetype=html

" When vimrc is edited, reload it
autocmd bufwritepost gvimrc source $MYGVIMRC
autocmd bufwritepost vimrc source $MYVIMRC

" Sudo write (,W)
noremap <leader>W :w !sudo tee %<CR>

" Toggle show tabs and trailing spaces (,c)
set lcs=tab:›\ ,trail:·,eol:↴,nbsp:_
set fcs=fold:-
nnoremap <silent> <leader>c :set nolist!<CR>

" Strip trailing whitespace (,ss)
function! StripWhitespace ()
    exec ':%s/ \+$//gc'
endfunction
noremap <leader>ss :call StripWhitespace ()<CR>

" Paste toggle (,p)
set pastetoggle=<leader>p
map <leader>p :set invpaste paste?<CR>

" Clear last search (,cs)
map <leader>cs <Esc>:noh<CR>

" Configure ctrlp
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_working_path_mode = 'rc'
set wildignore+=*/tmp/*,*.so,*.swp,*.zip     " MacOSX/Linux
set wildignore+=*\\tmp\\*,*.swp,*.zip,*.exe  " Windows
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/]\.(git|hg|svn)$',
  \ 'file': '\v\.(exe|so|dll|d|o|a|jpg|png|gif|pdf)$',
  \ 'link': 'some_bad_symbolic_links',
  \ }
let g:ctrlp_prompt_mappings = {
  \ 'AcceptSelection("e")': [],
  \ 'AcceptSelection("t")': ['<cr>', '<c-m>'],
  \ }
