#!/usr/bin/env bash

alias vi='vim'

# Enable PHP to be used with the mongoose server
alias mongoose_php="mongoose -C cgi,php -I /usr/local/bin/php-cgi"

# Convert PostScript file to PDF booklet
function ps2booklet(){
    if [ -z "$1" ]; then
        echo "Usage: ps2booklet (input.[e]ps)";
        return 1;
    fi
    local temp1=$(mktemp)
    local temp2=$(mktemp)
    psbook $1 $temp1 &&
    psnup -2 $temp1 $temp2 &&
    ps2pdf $temp2 ${1%%.*}.pdf &&
    rm $temp1 &&
    rm $temp2;
}

# Batch conversion of PCM files in current directory
function pcmto() {
    if [ -z "$1" ]; then
        echo "Usage: pcmto (format)";
        return 1;
    fi
    if [ "$1" == "spx" ]; then
        find . -maxdepth 1 -name "*.pcm" | sed -e "s/.pcm$//" | xargs -i speexenc --rate 16000 --16bit "{}.pcm" "{}.$1";
    elif [ "$1" == "mp3" ]; then
        find . -maxdepth 1 -name "*.pcm" | sed -e "s/.pcm$//" | xargs -i lame -r -m m -s 16 -b 16 "{}.pcm" "{}.$1";
    else
        find . -maxdepth 1 -name "*.pcm" | sed -e "s/.pcm$//" | xargs -i sox -t raw -r 16000 -e signed -b 16 -c 1 "{}.pcm" "{}.$1";
    fi
}
function pcmfrom() {
    if [ -z "$1" ]; then
        echo "Usage: pcmfrom (format)";
        return 1;
    fi
    if [ "$1" == "spx" ]; then
        find . -maxdepth 1 -name "*.$1" | sed -e "s/.$1$//" | xargs -i speexdec "{}.$1" "{}.pcm";
    else
        find . -maxdepth 1 -name "*.$1" | sed -e "s/.$1$//" | xargs -i sox "{}.$1" -t raw "{}.pcm";
    fi
}

alias cgdbpc='cgdb -d gdb -x $HOME/dotfiles/utils/pal_thread.gdb'

# Take a screenshot and save it on the desktop
function sshot() {
    DATE=`date +%Y-%m-%d\ %H-%M`
    import -window root "$HOME/Bureau/screenshot_$DATE.png"
}

# Generic Colorizer
alias cl='/usr/bin/grc -es --colour=auto'
alias configure='cl ./configure'
alias diff='cl diff'
alias make='cl make'
alias gcc='cl gcc'
alias arm-elf-gcc='cl arm-elf-gcc'
alias g++='cl g++'
alias as='cl as'
alias gas='cl gas'
alias ld='cl ld'
alias netstat='cl netstat'
alias ping='cl ping'
alias traceroute='cl /usr/sbin/traceroute'
