#!/usr/bin/env bash

alias vi='vim'

# Enable PHP to be used with the mongoose server
alias mongoose_php="mongoose -C cgi,php -I /usr/local/bin/php-cgi"

# Convert PostScript file to PDF booklet
function ps2booklet(){
    if [ -z "$1" ]; then
        echo "Usage: ps2booklet (input.[e]ps)";
        return 1;
    fi
    psbook $1 /tmp/book.ps &&
    psnup -2 /tmp/book.ps /tmp/booklet.ps &&
    ps2pdf /tmp/booklet.ps ${1%%.*}.pdf &&
    rm /tmp/book.ps &&
    rm /tmp/booklet.ps;
}

# Use ranger as a directory switcher
function ranger-cd {
  ranger --choosedir=/tmp/chosen
  if [ -f /tmp/chosen -a "$(cat /tmp/chosen)" != "$(pwd | tr -d "\n")" ]; then
    cd "$(cat /tmp/chosen)"
  fi
  rm -f /tmp/chosen
}
bind '"\C-o":"ranger-cd\C-m"'

# Batch conversion of PCM files in current directory
function pcmto() {
    if [ -z "$1" ]; then
        echo "Usage: pcmto (format)";
        return 1;
    fi
    find . -maxdepth 1 -name "*.pcm" | sed -e "s/.pcm$//" | xargs -i sox -t raw -r 16000 -e signed -b 16 -c 1 {}.pcm {}.$1;
}
function pcmfrom() {
    if [ -z "$1" ]; then
        echo "Usage: pcmfrom (format)";
        return 1;
    fi
    find . -maxdepth 1 -name "*.$1" | sed -e "s/.$1$//" | xargs -i sox {}.$1 -t raw {}.pcm;
}

alias cgdbpc='cgdb -d gdb -x $HOME/dotfiles/utils/pal_thread.gdb'
